osx_image: xcode8.3
dist: trusty
language: c
os:
  - osx
jobs:
  include:
    - os: osx
cache:
  directories:
    - node_modules
    - '$HOME/.electron'
    - '$HOME/.cache'
addons:
  apt:
    packages:
      - libgnome-keyring-dev
      - icnsutils
install:
  - nvm install 10
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - source ~/.bashrc
  - yarn

script:
  - yarn run build:darwin
  - yarn run zip

deploy:
  provider: releases
  cleanup: false
  skip_cleanup: true
  token: $GH_TOKEN
  file: build/shadow-websocket-gui-darwin-x64.tar.gz
  draft: false
  overwrite: true
  on:
    tags: on
